In [1]:
import pandas as pd
import json
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 5)


top_table = pd.read_csv('top.csv', index_col = 0)
bottom_table = pd.read_csv('bottom.csv', index_col = 0)

with open('test.json') as json_file:
    header = json.load(json_file)

In [2]:
#Combining top and bottom tables

#Add RLP suffix to bottom table
#Running Line Preview
#for i in range(2,len(list(bottom_table))):
#    bottom_table.columns.values[i] = "RLP_{}".format(bottom_table.columns.values[i])
    
#Dropping horse name for merge
bottom_table = bottom_table.drop("Horse Name", axis = 1)
bottom_table

,Pgm,Start,1/4,3/8,Str,Fin,1/4_length_behind,3/8_length_behind,Str_length_behind,Fin_length_behind
0,4.0,3.0,2,2,2,1,1/2,1/2,Head,Nose
1,6.0,2.0,3,3,1,2,1/2,1/2,Head,Nose
2,1.0,5.0,5,5,4,3,7 1/2,7,5,3/4
3,2.0,4.0,4,4,5,4,3 1/2,4 1/2,5 1/4,1 1/2
4,3.0,1.0,1,1,3,5,1/2,1/2,2,3 1/2

In [3]:

merged_df = top_table.join(bottom_table, on = "Pgm", rsuffix = "_RLP")

In [4]:
merged_df

,Last Raced,Pgm,Horse Name (Jockey),PP,Start,1/4,3/8,Str,Fin,Odds,Comments,Last Raced_super_script,1/4_length_behind,3/8_length_behind,Str_length_behind,Fin_length_behind,Wgt,M/E,Pgm_RLP,Start_RLP,1/4_RLP,3/8_RLP,Str_RLP,Fin_RLP,1/4_length_behind_RLP,3/8_length_behind_RLP,Str_length_behind_RLP,Fin_length_behind_RLP
0,2Jul22 MTH,4.0,"Wild Mule (Jimenez, Albin)",4.0,3.0,2,2,2,1,0.90*,"battled back, got nod",2 1,Head,Head,2,Nose,118,L,3.0,1.0,1.0,1.0,3.0,5.0,1/2,1/2,2,3 1/2
1,2Jul22 MTH,6.0,"Rol Again Dancer (Rodriguez, Angel)",5.0,2.0,3,3,1,2,1.50,"vied 3w, led, missed",6 1,3,4,Head,3/4,118,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30Jun22 DEL,1.0,"Bright Forecast (Ferrer, Jose)",1.0,5.0,5,5,4,3,4.70,"off slowly, rallied",2 1,NaN,NaN,Head,3/4,118,L,6.0,2.0,3.0,3.0,1.0,2.0,1/2,1/2,Head,Nose
3,22Jul22 MTH,2.0,"Running Right by U (Vargas, Jr., Jorge)",2.0,4.0,4,4,5,4,14.40,"inside, no rally",1 1,4,2 1/2,NaN,2,118,L,1.0,5.0,5.0,5.0,4.0,3.0,7 1/2,7,5,3/4
4,30Jul22 MTH,3.0,"Run Happy Pappy (Torres, Jomar)",3.0,1.0,1,1,3,5,14.10,"dueled inside, faded",5 7,1/2,1/2,3,NaN,118,L b,2.0,4.0,4.0,4.0,5.0,4.0,3 1/2,4 1/2,5 1/4,1 1/2

In [5]:
for field,value in header.items():
    merged_df[field] = value

In [6]:
merged_df

,Last Raced,Pgm,Horse Name (Jockey),PP,Start,1/4,3/8,Str,Fin,Odds,Comments,Last Raced_super_script,1/4_length_behind,3/8_length_behind,Str_length_behind,Fin_length_behind,Wgt,M/E,Pgm_RLP,Start_RLP,1/4_RLP,3/8_RLP,Str_RLP,Fin_RLP,1/4_length_behind_RLP,3/8_length_behind_RLP,Str_length_behind_RLP,Fin_length_behind_RLP,track,date,race_num,criteria,claiming_price,track_length,purse,weather,track_type,off_time,start,race_type
0,2Jul22 MTH,4.0,"Wild Mule (Jimenez, Albin)",4.0,3.0,2,2,2,1,0.90*,"battled back, got nod",2 1,Head,Head,2,Nose,118,L,3.0,1.0,1.0,1.0,3.0,5.0,1/2,1/2,2,3 1/2,Monmouth Park,"August 27, 2022",1,TWO YEAR OLDS WHICH HAVE BROKEN THEIR MAIDEN F...,"$50,000",Five And One Half Furlongs On The Dirt,"$45,000",Clear,Fast,12:16,Good for all except 1,allowance claiming
1,2Jul22 MTH,6.0,"Rol Again Dancer (Rodriguez, Angel)",5.0,2.0,3,3,1,2,1.50,"vied 3w, led, missed",6 1,3,4,Head,3/4,118,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Monmouth Park,"August 27, 2022",1,TWO YEAR OLDS WHICH HAVE BROKEN THEIR MAIDEN F...,"$50,000",Five And One Half Furlongs On The Dirt,"$45,000",Clear,Fast,12:16,Good for all except 1,allowance claiming
2,30Jun22 DEL,1.0,"Bright Forecast (Ferrer, Jose)",1.0,5.0,5,5,4,3,4.70,"off slowly, rallied",2 1,NaN,NaN,Head,3/4,118,L,6.0,2.0,3.0,3.0,1.0,2.0,1/2,1/2,Head,Nose,Monmouth Park,"August 27, 2022",1,TWO YEAR OLDS WHICH HAVE BROKEN THEIR MAIDEN F...,"$50,000",Five And One Half Furlongs On The Dirt,"$45,000",Clear,Fast,12:16,Good for all except 1,allowance claiming
3,22Jul22 MTH,2.0,"Running Right by U (Vargas, Jr., Jorge)",2.0,4.0,4,4,5,4,14.40,"inside, no rally",1 1,4,2 1/2,NaN,2,118,L,1.0,5.0,5.0,5.0,4.0,3.0,7 1/2,7,5,3/4,Monmouth Park,"August 27, 2022",1,TWO YEAR OLDS WHICH HAVE BROKEN THEIR MAIDEN F...,"$50,000",Five And One Half Furlongs On The Dirt,"$45,000",Clear,Fast,12:16,Good for all except 1,allowance claiming
4,30Jul22 MTH,3.0,"Run Happy Pappy (Torres, Jomar)",3.0,1.0,1,1,3,5,14.10,"dueled inside, faded",5 7,1/2,1/2,3,NaN,118,L b,2.0,4.0,4.0,4.0,5.0,4.0,3 1/2,4 1/2,5 1/4,1 1/2,Monmouth Park,"August 27, 2022",1,TWO YEAR OLDS WHICH HAVE BROKEN THEIR MAIDEN F...,"$50,000",Five And One Half Furlongs On The Dirt,"$45,000",Clear,Fast,12:16,Good for all except 1,allowance claiming

In [7]:
top_table_2 = pd.read_csv('top_2.csv', index_col = 0)
bottom_table_2 = pd.read_csv('bottom_2.csv', index_col = 0)

with open('test_2.json') as json_file:
    header_2 = json.load(json_file)
    
#Dropping horse name for merge
bottom_table_2 = bottom_table_2.drop("Horse Name", axis = 1)
merged_df_2 = top_table_2.join(bottom_table_2, on = "Pgm", rsuffix = "_RLP")
for field,value in header_2.items():
    merged_df_2[field] = value
merged_df_2

,Last Raced,Pgm,Horse Name (Jockey),PP,Start,1/4,1/2,3/4,Str,Fin,Odds,Comments,Last Raced_super_script,1/4_length_behind,1/2_length_behind,3/4_length_behind,Str_length_behind,Fin_length_behind,Wgt,M/E,Pgm_RLP,Start_RLP,1/4_RLP,1/2_RLP,3/4_RLP,Str_RLP,Fin_RLP,1/4_length_behind_RLP,1/2_length_behind_RLP,3/4_length_behind_RLP,Str_length_behind_RLP,Fin_length_behind_RLP,track,date,race_num,criteria,claiming_price,track_length,purse,weather,track_type,off_time,start,race_type
0,5Aug22 MTH,5.0,"Kingdom On Paws (Jimenez, Albin)",4.0,7.0,6,6,5,3,1,2.20*,"steadied start,p",5 3,Head,1,2,1 1/2,Neck,118,L bf,7.0,2.0,3.0,5.0,6.0,6.0,6.0,Head,1 3/4,3 3/4,8,11 1/,Monmouth Park,"August 27, 2022",2,"(PLUS UP TO 40% NJB) FOR MAIDENS, THREE YEARS ...","$40,000,",One And One Sixteenth Miles On The Turf,"$31,000",Clear,Firm,12:49,Good for all,maiden claiming
1,15Aug22 MTH,4.0,"Office Etiquette (Rowland, Madeline)",3.0,6.0,7,7,2,1,2,2.70,"steady start, 4w",3,NaN,NaN,1/2,1/2,3,110,L b,8.0,5.0,4.0,3.0,3.0,5.0,5.0,1 3/4,1/2,1/2,6,7 1/4,Monmouth Park,"August 27, 2022",2,"(PLUS UP TO 40% NJB) FOR MAIDENS, THREE YEARS ...","$40,000,",One And One Sixteenth Miles On The Turf,"$31,000",Clear,Firm,12:49,Good for all,maiden claiming
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,30Jul22 MTH,7.0,"The Big Calico (Jimenez, Manny)",6.0,2.0,3,5,6,6,6,22.50,"3w, btwn, faded",4 5,1 1/2,1,2,4,4,119,L bf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Monmouth Park,"August 27, 2022",2,"(PLUS UP TO 40% NJB) FOR MAIDENS, THREE YEARS ...","$40,000,",One And One Sixteenth Miles On The Turf,"$31,000",Clear,Firm,12:49,Good for all,maiden claiming
6,14Aug22 MTH,1.0,"Destiny Joy (Gonzalez, Jorge)",1.0,1.0,1,2,7,7,7,50.60,"vied inside, gav",11,Head,Head,NaN,NaN,NaN,118,L b,4.0,6.0,7.0,7.0,2.0,1.0,2.0,3 1/2,3 3/4,Head,1/2,Nec,Monmouth Park,"August 27, 2022",2,"(PLUS UP TO 40% NJB) FOR MAIDENS, THREE YEARS ...","$40,000,",One And One Sixteenth Miles On The Turf,"$31,000",Clear,Firm,12:49,Good for all,maiden claiming

In [8]:
    df = pd.merge(merged_df, merged_df_2, how = 'outer')

In [9]:
df.to_csv('merged.csv')

PermissionError: [Errno 13] Permission denied: 'merged.csv'

In [10]:
df

,Last Raced,Pgm,Horse Name (Jockey),PP,Start,1/4,3/8,Str,Fin,Odds,Comments,Last Raced_super_script,1/4_length_behind,3/8_length_behind,Str_length_behind,Fin_length_behind,Wgt,M/E,Pgm_RLP,Start_RLP,1/4_RLP,3/8_RLP,Str_RLP,Fin_RLP,1/4_length_behind_RLP,3/8_length_behind_RLP,Str_length_behind_RLP,Fin_length_behind_RLP,track,date,race_num,criteria,claiming_price,track_length,purse,weather,track_type,off_time,start,race_type,1/2,3/4,1/2_length_behind,3/4_length_behind,1/2_RLP,3/4_RLP,1/2_length_behind_RLP,3/4_length_behind_RLP
0,2Jul22 MTH,4.0,"Wild Mule (Jimenez, Albin)",4.0,3.0,2,2.0,2,1,0.90*,"battled back, got nod",2 1,Head,Head,2,Nose,118,L,3.0,1.0,1.0,1.0,3.0,5.0,1/2,1/2,2,3 1/2,Monmouth Park,"August 27, 2022",1,TWO YEAR OLDS WHICH HAVE BROKEN THEIR MAIDEN F...,"$50,000",Five And One Half Furlongs On The Dirt,"$45,000",Clear,Fast,12:16,Good for all except 1,allowance claiming,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2Jul22 MTH,6.0,"Rol Again Dancer (Rodriguez, Angel)",5.0,2.0,3,3.0,1,2,1.50,"vied 3w, led, missed",6 1,3,4,Head,3/4,118,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Monmouth Park,"August 27, 2022",1,TWO YEAR OLDS WHICH HAVE BROKEN THEIR MAIDEN F...,"$50,000",Five And One Half Furlongs On The Dirt,"$45,000",Clear,Fast,12:16,Good for all except 1,allowance claiming,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,30Jul22 MTH,7.0,"The Big Calico (Jimenez, Manny)",6.0,2.0,3,NaN,6,6,22.50,"3w, btwn, faded",4 5,1 1/2,NaN,4,4,119,L bf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Monmouth Park,"August 27, 2022",2,"(PLUS UP TO 40% NJB) FOR MAIDENS, THREE YEARS ...","$40,000,",One And One Sixteenth Miles On The Turf,"$31,000",Clear,Firm,12:49,Good for all,maiden claiming,5.0,6.0,1,2,NaN,NaN,NaN,NaN
11,14Aug22 MTH,1.0,"Destiny Joy (Gonzalez, Jorge)",1.0,1.0,1,NaN,7,7,50.60,"vied inside, gav",11,Head,NaN,NaN,NaN,118,L b,4.0,6.0,7.0,NaN,1.0,2.0,3 1/2,NaN,1/2,Nec,Monmouth Park,"August 27, 2022",2,"(PLUS UP TO 40% NJB) FOR MAIDENS, THREE YEARS ...","$40,000,",One And One Sixteenth Miles On The Turf,"$31,000",Clear,Firm,12:49,Good for all,maiden claiming,2.0,7.0,Head,NaN,7.0,2.0,3 3/4,Head

In [ ]:
bottom_table_2